### DISCUSSION TITLE
VPN Network

### DISCUSSION THREAD

**Discussion by KnuffigerMaxi** [ahembree/ansible-hms-docker#116] [Polls]
VPN Network with Transmission or qbittorrent with gluetun

**Comment by ahembree** [comment]
Started a new branch for this a while ago but not sure when I'll get around to it: https://github.com/ahembree/ansible-hms-docker/tree/add-gluetun-and-dl-clients

**Reply by KnuffigerMaxi** [reply]
qbittorrent would be super cool action

**Reply by ahembree** [reply]
qbittorrent and deluge are on the roadmap when gluetun is implemented

**Comment by ahembree** [comment]
I've done a little testing, and qBittorrent does not route all of its traffic through gluetun when using `network_mode: 'service:gluetun'` on the qbittorrent container, my router and IDS is picking up traffic around the DHT ping requests but the qbittorrent shows it has the VPN IP when running `curl icanhazip.com` within it:

![image](https://github.com/user-attachments/assets/64fe1f66-0ea3-4603-907c-25d47bd7c278)

So I will most likely be implementing qbittorrent and deluge with containers that already have the VPN connection built in, like `binhex/arch-qbittorrentvpn` and `binhex/arch-delugevpn` so connections aren't leaked, but so far I don't like how it saves VPN credentials to a text file that is readable by anyone (mode `0775`) and in plaintext in the docker logs...

Is there another use case where gluetun could be used other than for a torrent container?

**Reply by KnuffigerMaxi** [reply]
[Is this right for you? ](https://www.reddit.com/r/qBittorrent/s/7CL06UCwC7)

**Reply by ahembree** [reply]
It would be a lot easier to just use a qBittorrent+VPN bundled container I think

**Reply by KnuffigerMaxi** [reply]
Yeah I think

**Comment by ahembree** [comment]
I've decided to not implement gluetun for a number of reasons:

* traffic leaks if VPN is not bundled with download client
* 3 download clients each with their own VPN connection should be sufficient (still haven't decided if I only want to allow 1 download client at a time or allow multiple)
* each download/VPN bundle comes with an HTTP proxy for other services to leverage to route traffic through VPN
* the qbittorrent and deluge containers I plan to implement support both openvpn and wireguard, just like gluetun

I'll close this discussion sometime next week if there's no good use case for gluetun, but will proceed with working on implementing qbittorrent and deluge

**Reply by KnuffigerMaxi** [reply]
Those are good test results, I'll take a look 😅

**Comment by ahembree** [comment]
qBittorrent and Deluge have now been added in https://github.com/ahembree/ansible-hms-docker/releases/tag/1.7

**Reply by KnuffigerMaxi** [reply]
Thanks for the effort to add the two clients, that makes it easier to use other clients. which are better explained in the trash guides as there are hardly any guides for transmission.
Also for tracker almost all use qbit + qbit_merge

**Comment by KnuffigerMaxi** [comment]
```yml
gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6464:6464   #qBittorrent web interface
      - Dein Forward Port:Dein Forward Port #qBittorrent torrent port
      - 9696:9696   #Prowlarr
      - 7878:7878   #Radarr
      - 8989:8989   #Sonarr
      - 7474:7474   #Autobrr
      - 8191:8191   #Flaresolverr
      - 5055:5055   #Jellyseerr
      - 5454:5454   #Notifiarr
      - 2468:2468   #cross-seed
    volumes:
      - /share/CACHEDEV1_DATA/Daten/Server/gluetun:/gluetun
    environment:
      - FIREWALL_OUTBOUND_SUBNETS=Dein Subnet
      - FIREWALL_VPN_INPUT_PORTS=Dein Forward Port
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_PRESHARED_KEY=
      - WIREGUARD_ADDRESSES=
      - SERVER_COUNTRIES=Netherlands
```
Then you can integrate each Docker container with the following. If you do this, you must then delete the port for the respective container and only declare it with gluetun.

```yml
network_mode: service:gluetun
depends_on:
- gluetun
```

@ahembree see my conf?

**Reply by KnuffigerMaxi** [reply]
```yml
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PUBLIC_KEY= # copy from config file
      - WIREGUARD_PRIVATE_KEY= # copy from config file
      - WIREGUARD_PRESHARED_KEY= # copy from config file
      - WIREGUARD_ADDRESSES= # copy from config file
      - SERVER_REGIONS= # optional, comma seperated list, no spaces after commas, make sure it matches the config you created
      - SERVER_COUNTRIES= # optional, comma seperated list, no spaces after commas, make sure it matches the config you created
      - SERVER_CITIES= # optional, comma seperated list, no spaces after commas, make sure it matches the config you created
      - FIREWALL_VPN_INPUT_PORTS= # mandatory, the port number AirVPN forwarded for you (from pool #1) should appear here
      - TZ= # choose timezone value from list at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones (e.g.: Asia/Tokyo)
    ports:
      - 8080:8080 # qbittorrent web GUI, port number can be changed BUT it must match WEBUI_PORT in qbittorrent service environment
      - (port forwarded from AirVPN):(port forwarded from AirVPN) # also place in TORRENTING_PORT field in qbittorrent service environment
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    environment:
      - PUID= # your desired user's number
      - PGID= # your desired user's group number
      - TZ= # choose timezone value from list at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - WEBUI_PORT=8080 # must match "qbittorrent web GUI" port number in gluetun's service above
      - TORRENTING_PORT=(port forwarded from AirVPN) # must match forwarded port number in gluetun's service above
    volumes:
      - /mnt/(your folder structure here):/config # directory you want to save your qbittorrent config files
      - /mnt/(your folder structure here):/downloads # qbittorrent download location
    restart: unless-stopped
    network_mode: "service:gluetun" # this is what forces qbittorrent to only use the VPN connection from gluetun
```
