### ISSUE TITLE
GeoIP ID and Key is needed

### ISSUE THREAD

**Issue by Ninja-FSE** [ahembree/ansible-hms-docker#10]
i have edited the file "roles -> hmsdocker -> defaults -> main.yml" and "templates -> docker-compose.yml.j2" to include MaxMind ID and Key for GeoIP

docker-compose.yml.j2

```
  authentik-geoipupdate:
    container_name: authentik-geoipupdate
    image: "maxmindinc/geoipupdate:latest"
    networks:
      - authentik_net
    volumes:
      - "authentik_geoip:/usr/share/GeoIP"
    env_file:
      - .env
    environment:
      GEOIPUPDATE_ACCOUNT_ID: "{{ authentik_maxmind_id }}"
      GEOIPUPDATE_LICENSE_KEY: "{{ authentik_maxmind_key }}"
      GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
      GEOIPUPDATE_FREQUENCY: "8"
```

hmsdocker -> defaults -> main.yml
```

#######################################################################
### Authentik settings
# This OR the option in the container map will enable or disable the Authentik container
authentik_enabled: yes
authentik_provision_config: no
authentik_api_token: ""
authentik_host: "http://authentik-server:9000" # leave this as default if you're using the default hms-docker configuration (really only used if you have a separate authentik server) default: "http://authentik-server:9000"
authentik_external_host: 'https://{{ hms_docker_container_map["authentik"]["proxy_host_rule"] }}.{{ hms_docker_domain }}' # This needs to match the host rule that routes traffic to the Authentik container
authentik_maxmind_id: "CHANGEME-MAXMIND-ID" # MaxMind.com ID
authentik_maxmind_key: "CHANGEME-MAXMIND-KEY" # Maxmind.com Secret Key
### End of authentik settings
#######################################################################
```
