### ISSUE TITLE
Quick Question - Adding other network services to Traefik

### ISSUE THREAD

**Issue by sferguson524** [ahembree/ansible-hms-docker#20]
How can I add some of my other network services to traefik? 

such as home assistant and BlueIris

**Comment by ahembree** [comment]
You will need to assign the Traefik network name to the container along with the correct labels, I've found this easiest to do in a `docker-compose.yml` file.

To list available Docker networks, you can run `docker network ls`. By default, the Traefik network is named `hms-docker_traefik_net`.

You can assign a network in a compose file by:

```yaml
...
    networks:
      - hms-docker_traefik_net
...
```

You will also need to add this to the end of the compose file so it knows about the network:

```yaml
...
networks:
  "hms-docker_traefik_net":
    external: true
...
```

The labels you will need are:

```yaml
...
    labels:
      - traefik.enable=true
      - traefik.http.services.{SERVICE NAME HERE}.loadbalancer.server.port={CONTAINER PORT HERE}
      - traefik.http.routers.{SERVICE NAME HERE}.rule=Host(`{HOST RULE HERE}`)
      - traefik.http.routers.{SERVICE NAME HERE}.middlewares=internal-ipwhitelist #optional, restricts the container to only be accessible via RFC1918 addresses
...
```

replace `{SERVICE NAME HERE}` with something like `hassos` or `blueiris`, it's just for traefik to give it a name

replace `{CONTAINER PORT HERE}` with the port the webserver runs on within the container, such as `8123` for Home Assistant.

replace `{HOST RULE HERE}` with the FQDN you want to access the container by (such as `homeassistant.example.com`), the root domain will need to match the root domain you use for the HMS-Docker project so TLS certificates work correctly.

**Comment by sferguson524** [comment]
What if they're external services running in my VMware environment, and not in Docker.  Both are separate VMs.

**Comment by ahembree** [comment]
There is a way, it just requires static config files instead. You'd have to update the `traefik.yml` config file to add a "directory watch", but any changes would be overwritten on the next playbook run, so I'm working on a way to implement this.

Source: https://doc.traefik.io/traefik/providers/file/

**Comment by sferguson524** [comment]
Excellent! Thanks!

**Comment by ahembree** [comment]
Just a small update on this... I think I have a basic implementation working, having trouble with adding Authentik on top of it though, seems to be some sort of caching issue somewhere, or the things I'm testing with just don't want to play nice 🤣 

Also as a side note: Traefik terminates the TLS, so the traffic from the host with Traefik on it to the external service (such as something on vmware) would not be encrypted, unless the target host also uses TLS

**Comment by sferguson524** [comment]
Awesome! looking forward to what you come up with.. I think I read somewhere that NZBget is deprecated, any plans to move to SABNZB?

**Comment by ahembree** [comment]
I've just added the Traefik external services (but doesn't include Authentik support unfortunately): https://github.com/ahembree/ansible-hms-docker/commit/514cd2d4ce9eb801e227c19fee0f44becfc7b0ec

I personally don't use NZB so I'm not super familiar with it, I've just heard it's another method to download stuff so I thought I'd include it. I just added the sabnzbd container as well: https://github.com/ahembree/ansible-hms-docker/commit/a13eaa5be7c2999d1e7cb498291d606b3c5aadf4

**Comment by ahembree** [comment]
If you want to quickly add the external services to your Traefik config, just paste the following into your variables file (such as `vars/custom.yml`)

```yml
# Enables or Disables watching a directory for Traefik static file configs, see https://doc.traefik.io/traefik/providers/file/#configuration-examples // default: "no"
# NOTE: Traefik is configured to use YAML syntax
traefik_ext_hosts_enabled: no
traefik_ext_hosts_configs_path: "{{ hms_docker_apps_path }}/traefik/config/static_confs/"
# Settings for each external host:
#    friendly_name: host1, # just a friendly name for it
#    subdomain_name: sub-example, # the subdomain that will be used to access the service (such as sub-example.example.com, where example.com is the hms_docker_domain you defined above)
#    backend_url: http://example.com, # the url of the service you want to proxy through traefik
#    enabled: yes, # enables or disables the route

traefik_ext_hosts_list: [
  {
    friendly_name: host1,
    subdomain_name: example-sub,
    backend_url: http://example.com,
    enabled: yes,
  },
  #{
  #  friendly_name: host2,
  #  subdomain_name: example.com,
  #  backend_url: http://example.com,
  #  enabled: yes,
  #},
]
```
