### ISSUE TITLE
transmission via authentik only secures transmission-proxy

### ISSUE THREAD

**Issue by TiiFuchs** [ahembree/ansible-hms-docker#35]
When enabling expose_to_public and authentik via container_map.yml for *transmission*, only the transmission-proxy.[domain] get's "secured". But via transmission.[domain] transmission itself is accessible without any authentication or whitelist.

What is the desired configuration to make transmission accessible under transmission.[domain] via authentik and nothing else?

**Comment by TiiFuchs** [comment]
The service `proxy-hms@docker` has the configured transmission.<domain> route and an additional transmission-proxy.<domain> route in traefik configured.
I didn't figure out where the transmission-proxy route comes from. It's not configured in any default or custom vars yml.

**Comment by TiiFuchs** [comment]
Looks like this in traefik:
![CleanShot 2023-09-20 at 11 27 14](https://github.com/ahembree/ansible-hms-docker/assets/1958744/60607423-d9f9-4d6b-84d1-21fc70d53c76)

The transmission-proxy route has the authentik-proxy-hms-transmission-midware@docker middleware, but the transmission route has not.

I'm confused because traefik says the transmission-proxy route comes from Docker provider. But in the docker-compose.yml this route is not even once mentioned in a traefik label.
`docker inspect` on the transmission-proxy container does not show any label either.

**Comment by ahembree** [comment]
>What is the desired configuration to make transmission accessible under transmission.[domain] via authentik and nothing else?

Enable Authentik and then in the `container_map.yml` for transmission (change `expose_to_public` if you need):
```yaml
...
  transmission:
    enabled: yes
    proxy_host_rule: transmission
    directory: yes
    traefik: yes
    authentik: yes
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: yes
...
```

After this, you will need to configure the Authentik Outpost by following https://github.com/ahembree/ansible-hms-docker/blob/master/docs/Authentik.md#important-note

I'm not sure why you're seeing the `transmission-proxy` as a rule since the proxy container is what actually has the traefik rule for `transmission`, I haven't been able to replicate this. Traefik also has `exposedByDefault` disabled, so there shouldn't be any sort of auto-detection doing this.
