### ISSUE TITLE
Changing proxy hostname

### ISSUE THREAD

**Issue by Ninja-FSE** [ahembree/ansible-hms-docker#9]
Changing the proxy hostname in "hms_docker_container_map" doesnt change in file "authentik_outpost.j2".

Example:

```
  sonarr:
    enabled: yes
    proxy_host_rule: tv
    directory: yes
    traefik: yes
    authentik: yes
    authentik_provider_type: proxy
    expose_to_public: yes
```

in authentik-sonarr.outpost.yml

```
log_level: info
docker_labels:
  traefik.enable: "true"
  traefik.http.services.authentik-proxy-REDACT-sonarr-service.loadbalancer.server.port: "9000"
  traefik.http.routers.authentik-proxy-REDACT-sonarr-router.rule: Host(`sonarr.REDACT`) && PathPrefix(`/outpost.goauthentik.io/`)
  traefik.http.middlewares.authentik-proxy-REDACT-sonarr-router.forwardauth.address: http://authentik-proxy-REDACT-sonarr:9000/outpost.goauthentik.io/>
  traefik.http.middlewares.authentik-proxy-REDACT-sonarr-router.forwardauth.trustForwardHeader: "true"
  traefik.http.middlewares.authentik-proxy-REDACT-sonarr-router.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-emai>
authentik_host: http://authentik-server:9000
authentik_host_browser: https://auth.REDACT
docker_network: REDACT_traefik_net
container_image: null
docker_map_ports: false
kubernetes_replicas: 1
kubernetes_namespace: default
object_naming_template: authentik-proxy-REDACT-sonarr
authentik_host_insecure: false
kubernetes_service_type: ClusterIP
kubernetes_image_pull_secrets: []
kubernetes_disabled_components: []
kubernetes_ingress_annotations: {}
kubernetes_ingress_secret_name: authentik-outpost-tls
```

And in traefik-dashboard i can see
`Host(`tv.REDACT`) && PathPrefix(`/outpost.goauthentik.io`) `

but no middleware.

If i however change Forward Auth to Proxy things work (in Providers)
